### ISSUE TITLE
Request for more information

### ISSUE THREAD

**Issue by santhoshanand** [p0larbeer/yii2-polymer#1]
please also specify your project connection with yii2 in the details information.
or step by step detail

**Comment by p0larbeer** [comment]
For example you install basic app in directory ~/basic via composer

```
composer create-project --prefer-dist yiisoft/yii2-app-basic ~/basic
```

after installation need run code in direcory ~/basic

```
composer require p0larbeer/yii2-polymer
```

then go to  in directory ~/basic/vendor/p0larbeer/yii2-polymer and run

```
bower install
```

done
